
cores: 8
latency-wait: 30
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 3
# Cluster submission
jobname: "{rule}.{jobid}"
max-jobs-per-second: 1
max-status-checks-per-second: 10
jobs: 32

cluster: "sbatch --mem={resources.mem_mb} --time={resources.runtime}"

# Job resources
default-resources:
  - mem_mb=2000
  - runtime='24h'